Configuration:
  Scene:
    title: UPV E-mail Masivo
    background: \#F0FFFF
  Buttons:
    background: \#7FFFD4
    text-fill: white
  Text:
    fonts:
      size: 20px
      weight: bold
      style: normal
  Logo: /src/main/resources/logo_upv_transparente.png